Added Tests and removed package level variables.
wso2-ballerina/package-sonarqube pull request #4
Opened 2018-04-03 09:22 UTC by hasithajayasundara

## Purpose
> The purpose of ths PR is to add tests to the SonarQube connector implementation.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2018-04-03 09:57 UTC, dimslee requested changes

2018-04-03 09:57 UTC, muthulee commented on sonarqube67/sonarqube_connector.bal
> +    } catch (error err) {
Even if you don't do try and catch  the error will be returned.

2018-04-03 11:22 UTC, Biruntha commented on sonarqube67/sonarqube_transformers.bal
>  transformer <json projectDetails, Project project> getProjectDetails() {
Can you convert transformer to function ?

2018-04-03 13:46 UTC, Biruntha approved these changes

2018-04-05 07:13 UTC, Biruntha commented on tests/test.bal
> +    var projectDetails = sonarqube -> getProject("siddhi");
Can we get the project key from constant file as you did in other test case?

2018-04-05 07:13 UTC, Biruntha commented
1. Can you add .ballerina folder/file inside the project? otherwise we will get the error "ballerina: cannot find package 'tests'"

2018-04-09 03:31 UTC, dimslee approved these changes

2018-04-09 03:32 UTC, merged

2018-04-09 03:56 UTC, vlgunarathne commented on sonarqube6/sonarqube_connector.bal
> +                    count = count + 1;
We can use "count +=1" also.

2018-04-09 03:59 UTC, vlgunarathne commented on sonarqube6/sonarqube_connector.bal
> +public function SonarQubeConnector::getComplexity(string projectKey) returns (int|error) {
Needs to have @Param for "projectKey"

2018-04-09 04:10 UTC, hasithajayasundara commented on sonarqube6/sonarqube_connector.bal
> +                    count = count + 1;
Changed this as suggested.

2018-04-09 04:10 UTC, hasithajayasundara commented on sonarqube6/sonarqube_connector.bal
> +public function SonarQubeConnector::getComplexity(string projectKey) returns (int|error) {
Added.